### ISSUE TITLE
Wrong Capacitor

### ISSUE THREAD

**Issue by toms001** [DuPAL-PAL-DUmper/DuPAL_Board#1]
Hi, a very cool project!
1x 0.22uF / 35v min electrolytic capacitor (bom) at the 7805 or 220uF?
Thanks, toms001

**Comment by hkzlab** [comment]
Hello, it's 0.22, but is also actually a non-critical value, as it is meant to smooth out the ingress from your power supply.
I myself used a 0.22uF in a build and a 0.47 in another because I had that one handy.
By all means, if you have a noisy psu increase it, even to 100uF if required.

**Comment by toms001** [comment]
ok, thank you. A last question about the 74HC(T) - does it matter if i choose 74HC or 74HCT? In the schematics there is a 74HC166 and at your bom is 74HCT166 listed.

**Comment by hkzlab** [comment]
Use an HCT for the 166, outputs from PALs that have TTL level signals will be picked up better.
You can use HC for the rest.
