### ISSUE TITLE
Some issues with capacitors

### ISSUE THREAD

**Issue by dillix** [DuPAL-PAL-DUmper/DuPAL_Board#2]
Hi, hkzlab! Thanks for cool project!

There is some issues with capacitors:
1) There is C5 electrolytic capacitor in BOM list. Can you provide it capacity?
2) I tried several types of through-hole ceramic bypass capacitors 100nF (C3, C8, C9, C10, C11, C12, C13, C14, C16, C17) , but all of them didn't fit under the cribs for chips, so I soldered smd ones. Can you provide a photo of your ones?

**Comment by hkzlab** [comment]
Fixed missing C5. Use an 1uF. If in doubt, refer to the schematics in the kicad project.

For the 100nF caps, either
- Find sockets with a larger space in the middle
- Mount them on the underside of the board.

![photo_2021-11-02_10-34-25](https://user-images.githubusercontent.com/603354/139822063-adc8afc7-73af-4660-8688-5da86187644d.jpg)
