### ISSUE TITLE
Specifications for the switch

### ISSUE THREAD

**Issue by hexbus** [DuPAL-PAL-DUmper/DuPAL_Board#4]
Greetings - do you have the specifications for the required switch?  i.e. spacing between pins, etc?

V/R,
Jon

**Comment by hkzlab** [comment]
I can't give you a model: I've designed it to use some junk no-name switches I had around, though it should be pretty standard:
The pitch between the holes is 2mm.
Only the center and right inner pins are used and connected (looking at the board from the component side, keeping the power switch component up), the rest is for support.
So if you find a switch that fits on the external holes and the center one, just put a blob of solder to connect the outer support pins with the nearest smaller pad of the inner pins.

**Comment by hexbus** [comment]
Great, that spacing helps me out quite a bit!  If you could please add the 2MM description to the BOM, I’ll let you know when I find a switch that works and give you the model!  Thanks!

**Comment by hexbus** [comment]
I've found a few that work:

[First one from DigiKey - right angle](https://www.digikey.com/en/products/detail/c&k/OS102011MA1QN1/1981430)

[Second one from DigiKey - straight](https://www.digikey.com/en/products/detail/c-k/OS102011MS2QN1/411602)

These are both rated for 12V, but only .1A.  Not sure how much current is going through this switch - do you have any thoughts as to the specs?

I also found a bunch of these for cheap [on eBay](https://www.ebay.com/itm/182535742300).  Same switch, apparently.

**Comment by hkzlab** [comment]
Hm, the component that will absorb the most, by far, will be the PAL you put on the board. I took some measurements years ago, but it seems I can't find where I put the notes. Current was usually slightly above the 100mA mark though.
Alas, none of the junk switches I used had markings on them.

You can also use the two external support units to connect the switch (4mm pitch) if you can't find something rated 0.2A, they're not connected to GND. You just need to put a blob of solder between the outer and the inner pins to restore connection (I actually did that on one of my protos).

Also, I usually use a lower voltage than 12, 7 or 8VDC is fine.

**Comment by hexbus** [comment]
Yeah, the eBay ones I found didn’t have any marking either.  I’ll have to see how well it works :-)

I agree we need something more slightly beefier than a 0.1.  I’ll need to burn a protected PAL/GAL and see if the noname eBay switch holds up.  

![D6961830-5473-4D43-988B-8DED581963BF](https://user-images.githubusercontent.com/36237579/167625372-c7d209c5-1c75-45d2-a33c-d115a609bc27.jpeg)

**Comment by JohnDMcMaster** [comment]
I just went through a build exercise and could submit a reference BOM if it was accepted into the README

WIP can be seen here: https://twitter.com/johndmcmaster/status/1525758218961440768

**Comment by hkzlab** [comment]
@JohnDMcMaster sure. Absolutely nothing against that.
Especially since life is really hectic for me now, so can't really work on this anymore for the foreseeable future, so every help is gladly accepted.
